site_name: JSmol viewer widget for Jupyter
site_description: 'JSmol viewer widget for Jupyter'
site_author: 'Adam Fekete'
repo_name: 'fekad/jupyter-jsmol'
repo_url: 'https://github.com/fekad/jupyter-jsmol'

docs_dir: docs/

nav:
  - Home: index.md
  - introduction.md
  - installation.md
  - Examples:
      - Index: examples/index.md
  - Development:
      - Installation: installation-dev.md
      - Issues on GitHub: https://github.com/fekad/jupyter-jsmol/issues


theme:
  name: material